### PR TITLE
FilePath class to handle filepaths on a sane way

### PR DESCRIPTION
**Pull request by Zardoz89**
Implements FilePath class that wraps a unicode string that represents a path. Also, handles searching and getting the base path to assets folder and other interesting special folders, like user config and local data storage.

FilePath  do some basic path operations on a sane cross-platafom way. Like
- Path creation from strings
- Concatenate '+' and append '/' paths
- Check file/dir existence
- Create whole directory structures
- Check if a path is valid
- Check if a path is an absolute path
- Get a subpath from a full path
- Get the basepath from a path (the folder where is a file or the father folder of a folder)
- Return a generic normalized string representation
- Return a OS native string representation
- Return a OS native string representation on the OS desired string format (*nix -> string ; windows -> wstring)

Also, now the whole code that handles paths to resources, uses now FilePath class, so would try to load the assets from the correct path. Try to copy assets to the folder where is TEC.exe, or execute TEC.exe on the same folder where is the assets folder.

### CODE REVIEW

**Comment by Zardoz89** [comment]
It's necessary to merge first tec-assets and then, put a commit to use the trillek/tec-assets repo. Actually it's pointing to my fork and a concrete branch.

**Comment by adam4813** [comment]
K I'll fix it when I merge.

**Comment by Zardoz89** [comment]
If I read correctly, would be necessary to setup ImGui::GetIO()  to the correct path for the ini file :
```
ImGuiIO& io = ImGui::GetIO();
io.IniFilename =  (FilePath::GetUserSettingsPath() / "imgui.ini").toString();
```
I would try to check it and do the proper commit.

**Comment by adam4813** [comment]
Seems valid.

**Comment by Zardoz89** [comment]
I'm thinking that on a future I could add a variadic constructor for FilePath, so instead of (for example GetUserSettingsPath() ) : 
```
FilePath ret;
....
ret = home;
+	ret /= u8".config";
+	ret /= app_name;
+	ret += PATH_SEPARATOR;
...
return ret;
```
Could be 
```
FilePath ret;
....
ret = FilePath(home, u8".config", app_name, PATH_SEPARATOR);
...
return ret;
```
So, could do a named return value optimization (ie not do a copy on return). But I think that this have a low priority.

**Comment by adam4813** [comment]
For now though let's focus on getting things working and not on engineering
every use case.

**Comment by Zardoz89** [comment]
Superseded by PR #44

**Pull request closed without merging**
