### PR TITLE
Deploy the tec file from travis builds on new tags

### PR DESCRIPTION
**Pull request by fahlmant**
The OAUTH token will need to be generated and added by owners of the repo.

### CODE REVIEW

**Comment by adam4813** [comment]
Is there a way to append -linux is such to the releaae name as Travis
doesn't build windows.

**Comment by milesrout** [comment]
Fixes #98

**Comment by milesrout** [comment]
Last time we built a release (see [here (v0.10)](https://github.com/trillek-team/tec/releases/tag/v0.10) for reference) we had two extra files (the source zip/tgz are automatically added by GitHub):

* trillek-0.10-release-linux.zip
* trillek-0.10-release-win32.zip

Currently this seems to upload just `TEC`, not a tarball. Is archiving up the binaries and assets - presumably without the source code - something we need to add as a separate travis build step?

**Comment by fahlmant** [comment]
@milesrout I believe we could tar up everything from this build into a tarball (or zip) and upload that in this same deploy block. I'll work on that. I have never used AppVeyor, but that will be where the windows tarball will be uploaded from. That will either be another commit on this PR, or a separate PR.

**Comment by adam4813** [comment]
I can get appveyor to package up. Just need to name them appropriately so people download the correct ones.

**Comment by milesrout** [comment]
@fahlmant While you're at it, could you make the Linux tarball an actual tarball - tar.gz - instead of zip? Thanks.

**Comment by milesrout** [comment]
We're no longer using Travis.

**Pull request closed without merging**
